# Generated by Django 4.2.6 on 2023-10-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(max_length=20)),
                ('titre', models.CharField(max_length=100)),
                ('annee', models.CharField(default=None, max_length=4)),
                ('quantite', models.IntegerField(default=1)),
                ('observation', models.CharField(default=None, max_length=256)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cale.auteur')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cale.edition')),
            ],
        ),
    ]
